#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

addons_dir=$PLUSHU_APPS_DIR/$1/addons

# for every addon in the destroying app's addons
for addon_path in "$addons_dir"/*; do
  # remove it first
  addon=${addon%$addon_dir/}
  "$PLUSHU_ROOT/lib/plushook" remove-addon $app $addon
done
