#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app=$1
addons_dir=$PLUSHU_APPS_DIR/$app/addons

# For instances where a glob has no matches we want an empty list
shopt -s nullglob

# for every addon in the destroying app's addons
for addon_path in "$addons_dir"/*; do
  # remove it first
  addon=${addon_path##*/}
  "$PLUSHU_ROOT/lib/plushook" remove-addon "$app" "$addon"
done
