#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -n "$PLUSHU_APP_NAME" ]]; then
  app=$PLUSHU_APP_NAME
elif [[ -n "$2" ]]; then
  app=$2
  shift
else
  echo "Missing app name" >&2
  exit 1
fi

app_dir=$PLUSHU_APPS_DIR/$app

# Check if app exists
if [[ ! -d "$app_dir" ]]; then
  echo "App not found: $app" >&2
  exit 1
fi

addon=$2

# If an addon name was specified
if [[ -n "$addon" ]]; then

  addon_path=$PLUSHU_APPS_DIR/$app/addons/$addon
  service_path=$PLUSHU_SERVICES_DIR/$addon

  # Print an error if the addon is already present
  if [[ -e "$addon_path" ]]; then
    echo "App '$app' already has addon '$addon'" >&2
    exit 1

  # If the service exists and isn't already added, add it
  elif [[ -d "$service_path" ]]; then
    "$PLUSHU_ROOT/lib/plushook" add-addon "$app" "$addon" "$3"

  # If there's no service by the given name
  else
    echo "Service '$addon' is not installed" >&2
    exit 1
  fi

# If no plugin name was specified
else
  echo "Missing name of addon to add" >&2
  exit 1
fi
