#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -n "$PLUSHU_APP_NAME" ]]; then
  app=$PLUSHU_APP_NAME
elif [[ -n "$2" ]]; then
  app=$2
  shift
else
  echo "Missing app name" >&2
  exit 1
fi

app_dir=$PLUSHU_APPS_DIR/$app

# Check if app exists
if [[ ! -d "$app_dir" ]]; then
  echo "App not found: $app" >&2
  exit 1
fi

addon=$2

# If an addon name was specified
if [[ -n "$addon" ]]; then

  addon_path=$PLUSHU_APPS_DIR/$app/addons/$addon
  service_path=$PLUSHU_SERVICES_DIR/$addon
  upgrade_script=$service_path/upgrade

  # If this app has this addon
  if [[ -e "$addon_path" ]]; then
    # And this addon can be upgraded
    if [[ -x "$upgrade_script" ]]; then
      "$PLUSHU_ROOT/lib/plushook" upgrade-addon "$app" "$addon"

    # If this addon doesn't have an "upgrade" executable
    else
      echo "Service '$addon' has no upgrade operation" >&2
      exit 1
    fi

  # If the addon isn't already added
  else
    echo "App '$app' has no addon '$addon'" >&2
    exit 1
  fi

# If no plugin name was specified
else
  echo "Missing name of addon to upgrade" >&2
  exit 1
fi
